// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conflictresolution.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import conflictresolution.proxies.microflows.Microflows;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This action applies a first wins strategy in which the last user that commited the object wins and the previous commited changes are ignored.
 */
public class ApplyLastWins extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __EditedSyncObject;
	private conflictresolution.proxies.SyncObject EditedSyncObject;

	public ApplyLastWins(IContext context, IMendixObject EditedSyncObject)
	{
		super(context);
		this.__EditedSyncObject = EditedSyncObject;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.EditedSyncObject = __EditedSyncObject == null ? null : conflictresolution.proxies.SyncObject.initialize(getContext(), __EditedSyncObject);

		// BEGIN USER CODE
		return Microflows.lastWins(super.getContext(), this.EditedSyncObject).getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ApplyLastWins";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
