// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conflictresolution.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import conflictresolution.proxies.microflows.Microflows;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This action creates a sync error which is stored for the current user and the specified sync object. Via the SyncValidation widget this message can be shown.
 */
public class CreateSyncError extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ErrorMessage;
	private IMendixObject __DatabaseSyncObject;
	private conflictresolution.proxies.SyncObject DatabaseSyncObject;

	public CreateSyncError(IContext context, java.lang.String ErrorMessage, IMendixObject DatabaseSyncObject)
	{
		super(context);
		this.ErrorMessage = ErrorMessage;
		this.__DatabaseSyncObject = DatabaseSyncObject;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.DatabaseSyncObject = __DatabaseSyncObject == null ? null : conflictresolution.proxies.SyncObject.initialize(getContext(), __DatabaseSyncObject);

		// BEGIN USER CODE
		Microflows.sUB_CreateSyncError(getContext(), DatabaseSyncObject, ErrorMessage);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CreateSyncError";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
