// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package inspections.proxies;

public class Inspection extends conflictresolution.proxies.SyncObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Inspections.Inspection";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CompanyName("CompanyName"),
		ContactPerson("ContactPerson"),
		Location("Location"),
		Phonenumber("Phonenumber"),
		_Revision("_Revision"),
		Inspection_Inspector("Inspections.Inspection_Inspector");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Inspection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Inspections.Inspection"));
	}

	protected Inspection(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject inspectionMendixObject)
	{
		super(context, inspectionMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Inspections.Inspection", inspectionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Inspections.Inspection");
	}

	/**
	 * @deprecated Use 'Inspection.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static inspections.proxies.Inspection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return inspections.proxies.Inspection.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static inspections.proxies.Inspection initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new inspections.proxies.Inspection(context, mendixObject);
	}

	public static inspections.proxies.Inspection load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return inspections.proxies.Inspection.initialize(context, mendixObject);
	}

	public static java.util.List<inspections.proxies.Inspection> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<inspections.proxies.Inspection> result = new java.util.ArrayList<inspections.proxies.Inspection>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Inspections.Inspection" + xpathConstraint))
			result.add(inspections.proxies.Inspection.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of CompanyName
	 */
	public final java.lang.String getCompanyName()
	{
		return getCompanyName(getContext());
	}

	/**
	 * @param context
	 * @return value of CompanyName
	 */
	public final java.lang.String getCompanyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompanyName.toString());
	}

	/**
	 * Set value of CompanyName
	 * @param companyname
	 */
	public final void setCompanyName(java.lang.String companyname)
	{
		setCompanyName(getContext(), companyname);
	}

	/**
	 * Set value of CompanyName
	 * @param context
	 * @param companyname
	 */
	public final void setCompanyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String companyname)
	{
		getMendixObject().setValue(context, MemberNames.CompanyName.toString(), companyname);
	}

	/**
	 * @return value of ContactPerson
	 */
	public final java.lang.String getContactPerson()
	{
		return getContactPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactPerson
	 */
	public final java.lang.String getContactPerson(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactPerson.toString());
	}

	/**
	 * Set value of ContactPerson
	 * @param contactperson
	 */
	public final void setContactPerson(java.lang.String contactperson)
	{
		setContactPerson(getContext(), contactperson);
	}

	/**
	 * Set value of ContactPerson
	 * @param context
	 * @param contactperson
	 */
	public final void setContactPerson(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactperson)
	{
		getMendixObject().setValue(context, MemberNames.ContactPerson.toString(), contactperson);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of Phonenumber
	 */
	public final java.lang.String getPhonenumber()
	{
		return getPhonenumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Phonenumber
	 */
	public final java.lang.String getPhonenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phonenumber.toString());
	}

	/**
	 * Set value of Phonenumber
	 * @param phonenumber
	 */
	public final void setPhonenumber(java.lang.String phonenumber)
	{
		setPhonenumber(getContext(), phonenumber);
	}

	/**
	 * Set value of Phonenumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhonenumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.Phonenumber.toString(), phonenumber);
	}

	/**
	 * @return value of Inspection_Inspector
	 */
	public final administration.proxies.Account getInspection_Inspector() throws com.mendix.core.CoreException
	{
		return getInspection_Inspector(getContext());
	}

	/**
	 * @param context
	 * @return value of Inspection_Inspector
	 */
	public final administration.proxies.Account getInspection_Inspector(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Inspection_Inspector.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Inspection_Inspector
	 * @param inspection_inspector
	 */
	public final void setInspection_Inspector(administration.proxies.Account inspection_inspector)
	{
		setInspection_Inspector(getContext(), inspection_inspector);
	}

	/**
	 * Set value of Inspection_Inspector
	 * @param context
	 * @param inspection_inspector
	 */
	public final void setInspection_Inspector(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account inspection_inspector)
	{
		if (inspection_inspector == null)
			getMendixObject().setValue(context, MemberNames.Inspection_Inspector.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Inspection_Inspector.toString(), inspection_inspector.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final inspections.proxies.Inspection that = (inspections.proxies.Inspection) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Inspections.Inspection";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
