// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package conflictresolution.proxies;

public class SyncObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject syncObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ConflictResolution.SyncObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_Revision("_Revision");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SyncObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ConflictResolution.SyncObject"));
	}

	protected SyncObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject syncObjectMendixObject)
	{
		if (syncObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ConflictResolution.SyncObject", syncObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ConflictResolution.SyncObject");

		this.syncObjectMendixObject = syncObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SyncObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static conflictresolution.proxies.SyncObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return conflictresolution.proxies.SyncObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static conflictresolution.proxies.SyncObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Inspections.Inspection", mendixObject.getType()))
			return inspections.proxies.Inspection.initialize(context, mendixObject);

		return new conflictresolution.proxies.SyncObject(context, mendixObject);
	}

	public static conflictresolution.proxies.SyncObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return conflictresolution.proxies.SyncObject.initialize(context, mendixObject);
	}

	public static java.util.List<? extends conflictresolution.proxies.SyncObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<conflictresolution.proxies.SyncObject> result = new java.util.ArrayList<conflictresolution.proxies.SyncObject>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ConflictResolution.SyncObject" + xpathConstraint))
			result.add(conflictresolution.proxies.SyncObject.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _Revision
	 */
	public final java.lang.Integer get_Revision()
	{
		return get_Revision(getContext());
	}

	/**
	 * @param context
	 * @return value of _Revision
	 */
	public final java.lang.Integer get_Revision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._Revision.toString());
	}

	/**
	 * Set value of _Revision
	 * @param _revision
	 */
	public final void set_Revision(java.lang.Integer _revision)
	{
		set_Revision(getContext(), _revision);
	}

	/**
	 * Set value of _Revision
	 * @param context
	 * @param _revision
	 */
	public final void set_Revision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _revision)
	{
		getMendixObject().setValue(context, MemberNames._Revision.toString(), _revision);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return syncObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final conflictresolution.proxies.SyncObject that = (conflictresolution.proxies.SyncObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ConflictResolution.SyncObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
